version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: bimser_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bimser #degistirelecek
      POSTGRES_PASSWORD: bimser_secret #degistirelecek
      POSTGRES_DB: bimser_docs
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bimser -d bimser_docs"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
